SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF

go

EXEC spALTER_TABLE 'ContD','Logico1','BIT DEFAULT 0'
GO
EXEC spALTER_TABLE 'ContD','Logico2','BIT DEFAULT 0'
go

