SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF

go

IF EXISTS(SELECT name 
	  FROM 	 sysobjects 
	  WHERE  name = N'DICOContIC_log' 
	  AND 	 type = 'U')
    DROP TABLE DICOContIC_log
GO

CREATE TABLE DICOContIC_log (
	   ContID		INT		 NOT NULL,
	   Empresa	VARCHAR(10) NULL,
	   FechaProcesamiento  DATETIME	NULL
)
GO