SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
GO


--Corregir rtegistro contable
EXEC xpDICOFixContReg '14',NULL,NULL,0


--Corregir ctas
DECLARE @OK INT, @OKRef VARCHAR(255)
EXEC xpDICOProcesarCtasAct '14',1,@OK OUTPUT,@OKRef OUTPUT