SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
GO
--SELECT dbo.fnDICOValidaCtaIC('215-202-000')
IF EXISTS(SELECT * FROM sysobjects WHERE TYPE='fn' AND NAME='fnDICOValidaCtaIC')
DROP FUNCTION fnDICOValidaCtaIC
GO
CREATE FUNCTION fnDICOValidaCtaIC(@Cuenta VARCHAR(35))
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @resultado VARCHAR(5)
	
	IF EXISTS(SELECT 1 FROM DICOCtasActualizar WHERE Cuenta=@Cuenta)
		SET @resultado='SI'
	ELSE
		SET @resultado='NO'

RETURN @resultado
END