SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
GO

IF NOT EXISTS(SELECT * FROM sysobjects AS s WHERE s.[type]='U' AND s.name='DICODesgloseContactoSI')
	CREATE TABLE DICODesgloseContactoSI(
		Estacion		INT				NOT NULL,
		ID				INT				NOT NULL,
		Empresa			VARCHAR(10)		NULL,
		Contacto		VARCHAR(10)		NULL,
		ContactoTipo	VARCHAR(15)		NULL,
		Cuenta			VARCHAR(30)		NULL,
		Sucursal		INT				NULL,
		Debe			FLOAT			NULL,
		Haber			FLOAT			NULL
	)